# Generated by Django 4.0.1 on 2022-06-06 09:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdjacencyMatrix',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matrix', models.TextField()),
                ('created_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'get_latest_by': 'created_at',
            },
        ),
        migrations.CreateModel(
            name='Line',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField()),
                ('walkline', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='LineMatrix',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matrix', models.TextField()),
                ('created_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'get_latest_by': 'created_at',
            },
        ),
        migrations.CreateModel(
            name='TramStop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('stopid', models.PositiveIntegerField(default=0)),
                ('stopnumber', models.PositiveIntegerField()),
                ('longitude', models.DecimalField(decimal_places=7, default=0, max_digits=10)),
                ('latitude', models.DecimalField(decimal_places=7, default=0, max_digits=10)),
                ('line', models.ManyToManyField(related_name='stops', to='api.Line')),
            ],
            options={
                'unique_together': {('name', 'stopnumber')},
            },
        ),
        migrations.CreateModel(
            name='LineTimetable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField()),
                ('time_since_0', models.PositiveIntegerField()),
                ('line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.line')),
                ('stop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.tramstop')),
            ],
        ),
        migrations.AddField(
            model_name='line',
            name='first_stop',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='startinglines', to='api.tramstop'),
        ),
        migrations.AddField(
            model_name='line',
            name='last_stop',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='endinglines', to='api.tramstop'),
        ),
        migrations.CreateModel(
            name='StopTimetable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timearray', models.TextField()),
                ('line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stoptables', to='api.line')),
                ('stop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stoptables', to='api.tramstop')),
            ],
            options={
                'unique_together': {('line', 'stop')},
            },
        ),
        migrations.CreateModel(
            name='LineMatrixCell',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('col', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='LineMcol', to='api.tramstop')),
                ('lines', models.ManyToManyField(null=True, to='api.Line')),
                ('row', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='LineMrow', to='api.tramstop')),
            ],
            options={
                'unique_together': {('col', 'row')},
            },
        ),
        migrations.CreateModel(
            name='AdjacencyMatrixCell',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.PositiveIntegerField()),
                ('col', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='colstop', to='api.tramstop')),
                ('lines', models.ManyToManyField(null=True, to='api.Line')),
                ('row', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rowstop', to='api.tramstop')),
            ],
            options={
                'unique_together': {('col', 'row')},
            },
        ),
    ]
