# Generated by Django 4.0.1 on 2022-06-06 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adjacencymatrixcell',
            name='lines',
            field=models.ManyToManyField(to='api.Line'),
        ),
        migrations.AlterField(
            model_name='linematrixcell',
            name='lines',
            field=models.ManyToManyField(to='api.Line'),
        ),
    ]
